### ISSUE TITLE
Core: tryExactlyOnce used, but FSharp specified as 4.5

### ISSUE THREAD

**Issue by ysangkok** [joemphilips/DotNetLightning#32]
https://github.com/joemphilips/DotNetLightning/blob/1a1caf3578fdf7d5fd270f516c6b6d280b4898fd/src/DotNetLightning.Core/Utils/NBitcoinExtensions.fs#L34

I am unsure whether it would be OK to upgrade FSharp?

tryExactlyOnce is available from FSharp 4.6, according to https://github.com/fsharp/fslang-design/blob/master/FSharp.Core-4.6.0/FS-1066-tryExactlyOne.md

**Comment by joemphilips** [comment]
I'm not sure about this either. let me search about FSharp and netstandard versioning.

**Comment by joemphilips** [comment]
By reading [Notes and Guidance on FSharp.Core](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#make-your-fsharp.core-references-explicit) more carefully,  I noticed current fsproj is not following the best practice,

### Current situation

right now it is specifying `FSharp.Core` by `Include`
https://github.com/joemphilips/DotNetLightning/blob/3db52fb3a5fa9fb209defc59e4ced9cf808271b0/src/DotNetLightning.Core/DotNetLightning.Core.fsproj#L71

But the sdk is actually ignoring this and it is using the version which comes together with the sdk. (In case of ci and my local machine, the version is probably 4.6+ so it successfully compiles, but if it is 4.5.4, it will fail because of `tryExtactlyOne` )
We should change this by changing `Include` to `Update`

### The way to go

According to the notes above, it is recommended to use 4.3.4, but this will cause too big change since we cannot use `outref` and [other F#4.5 goodies](https://devblogs.microsoft.com/dotnet/announcing-f-4-5/) .
 
But I think we can just specify it to use 4.7.0 (or maybe 4.6 if there is any problem with the CI or so.), it is unlikely that the project which must use F# version 4.5 (or older) will use this package.

**Comment by knocte** [comment]
Next time you should put all that info in the commit message ;) :)
