### ISSUE TITLE
FundingLocked sent only when MaxMinimumDepth reached

### ISSUE THREAD

**Issue by ysangkok** [joemphilips/DotNetLightning#38]
It seems to me that DotNetLightning will only send FundingLocked once the depth from PeerLimits have been reached. But isn't that too long? If we open a channel to a counterparty that sets [minimum_depth](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#the-accept_channel-message) to a lower number, wouldn't it make sense to send FundingLocked then?

**Comment by knocte** [comment]
@joemphilips do you agree about addressing this issue?

**Comment by joemphilips** [comment]
@ysangkok Yes, you are right. This is bug.

**Comment by ysangkok** [comment]
@joemphilips Do you want me to try to prepare a fix PR?

**Comment by joemphilips** [comment]
@ysangkok Yes that will be very helpful.
(Sorry that I've been busy that I cannot do it by myself... I think I can spare time during new yea'rs holiday.)

I remember that when I ported this part from eclair, the original code was doing something different so that it enables 0-conf channel opening.
I decided to not follow the code since it seemed too risky (at least for now.)

**Comment by knocte** [comment]
I agree 0-conf is risky, but DNL is a library and should allow the consumer what it wants (in geewallet's case, we want 2 confs).
