### ISSUE TITLE
Unable to find package ResultUtils. No packages exist with this id in source(s): nuget.org

### ISSUE THREAD

**Issue by ysangkok** [joemphilips/DotNetLightning#41]
I suspect I am getting this error in geewallet because I am not using your feed. Would it be possible to publish this package on Nuget? Thanks.

**Comment by joemphilips** [comment]
OK

**Comment by knocte** [comment]
Wait, I don't think it's a problem about feeds because ResultUtils sources are in this repo.

**Comment by joemphilips** [comment]
Yes, it is not a problem of feeds. ResultUtils is referenced by `ProjectReference` from `DotNetLightning.Core` , so it should not behave as  a dependency, but (weirdly) a nuget is treating it as a deps and tries to resolve from the feed, thus fails.

Probably including ResultUtils and TaskUtils as a PrivateAssets will solve the problem. Which I first thought its not ideal because if the consumer tries to use `FsToolKit.ErrorHandling` than it will cause some kind of incompatibility issue, but thinking carefully, exposing only simple `Result` will not cause those kind of problem.

So any way, I will first try #42 If it did not work well, I make another PR if it did not work well.

**Comment by joemphilips** [comment]
Yeah, this is probably the exact same issue which @knocte raise in #14 , and solved in #16 , I've been forgotten about it completely.

**Comment by joemphilips** [comment]
Yep, seems it is fixed now.
